<a href="https://colab.research.google.com/github/Fulim13/Pytorch_Learning/blob/main/02_Tensor_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Everything in pytorch is based on Tensor operations.
# A tensor can have different dimensions
# so it can be 1d, 2d, or even 3d and higher

In [ ]:
# scalar, vector, matrix, tensor

# torch.empty(size): uninitiallized
x = torch.empty(1)  # scalar
print(x)

tensor([0.])


In [ ]:
x = torch.empty(3)  # vector, 1D
print(x)

tensor([-3.8546e-34,  9.3186e-43,  0.0000e+00])


In [ ]:
x = torch.empty(2, 3)  # matrix, 2D
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
x = torch.empty(2, 2, 2, 3)  # tensor, 4 dimensions
print(x)

tensor([[[[-3.9726e-34,  9.3186e-43,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.8705, 0.8740, 0.2243],
        [0.8138, 0.0290, 0.4090],
        [0.6880, 0.1832, 0.1098],
        [0.9763, 0.7629, 0.6506],
        [0.9682, 0.5157, 0.5089]])


In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# check size
print(x.size())

torch.Size([5, 3])


In [ ]:
# check data type
print(x.dtype)

torch.float32


In [ ]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [ ]:
# check type
print(x.dtype)

torch.float16


In [ ]:
# construct from python list
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [ ]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [ ]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1637, 0.1806],
        [0.3494, 0.4243]])
tensor([[0.3583, 0.7604],
        [0.1176, 0.2907]])


In [ ]:
# elementwise addition
z = x + y
z2 = torch.add(x, y)
print(z)
print(z2)

tensor([[0.5220, 0.9410],
        [0.4670, 0.7151]])
tensor([[0.5220, 0.9410],
        [0.4670, 0.7151]])


In [ ]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
z.add_(x)
print(z)

tensor([[0.6857, 1.1215],
        [0.8165, 1.1394]])


In [ ]:
# substraction
z = x - y
z = torch.sub(x, y)
print(z)

tensor([[-0.1945, -0.5798],
        [ 0.2318,  0.1336]])


In [ ]:
# multiplication
z = x * y
z = torch.mul(x, y)
print(z)

tensor([[0.0587, 0.1373],
        [0.0411, 0.1234]])


In [ ]:
# division
z = x / y
z = torch.div(x, y)
print(z)

tensor([[0.4570, 0.2375],
        [2.9716, 1.4596]])


In [ ]:
# Slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0])  # all rows, column 0
print(x[1, :])  # row 1, all columns
print(x[1, 1])  # element at 1, 1

tensor([[0.6940, 0.6637, 0.2004],
        [0.7846, 0.0184, 0.3658],
        [0.3973, 0.0232, 0.1009],
        [0.7253, 0.9164, 0.9660],
        [0.8640, 0.2613, 0.8391]])
tensor([0.6940, 0.7846, 0.3973, 0.7253, 0.8640])
tensor([0.7846, 0.0184, 0.3658])
tensor(0.0184)


In [ ]:
# Get the actual value if only 1 element in your tensor
print(x[1, 1].item())

0.01843160390853882


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size

print(x, x.size())
print(y, y.size())
print(z, z.size())

tensor([[ 0.8092,  0.7406, -0.3241,  0.1249],
        [-1.4173, -1.3692, -0.3851,  0.2380],
        [-0.9106,  1.6567, -1.4502, -2.2673],
        [ 0.6244, -0.3969,  0.4928,  1.4626]]) torch.Size([4, 4])
tensor([ 0.8092,  0.7406, -0.3241,  0.1249, -1.4173, -1.3692, -0.3851,  0.2380,
        -0.9106,  1.6567, -1.4502, -2.2673,  0.6244, -0.3969,  0.4928,  1.4626]) torch.Size([16])
tensor([[ 0.8092,  0.7406, -0.3241,  0.1249, -1.4173, -1.3692, -0.3851,  0.2380],
        [-0.9106,  1.6567, -1.4502, -2.2673,  0.6244, -0.3969,  0.4928,  1.4626]]) torch.Size([2, 8])


In [ ]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    print(y)

    # or just use strings ``.to("cuda")``
    x = x.to(device)
    print(x)

    z = x + y
    print(z)

    # z = z.numpy() # not possible because numpy cannot handle GPU tenors

    # Move the tensor to CPU and then convert it to NumPy array
    z_cpu = z.cpu()  # Move tensor to CPU
    z_numpy = z_cpu.numpy()  # Convert tensor to NumPy array
    print(z_numpy)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[ 0.8092,  0.7406, -0.3241,  0.1249],
        [-1.4173, -1.3692, -0.3851,  0.2380],
        [-0.9106,  1.6567, -1.4502, -2.2673],
        [ 0.6244, -0.3969,  0.4928,  1.4626]], device='cuda:0')
tensor([[ 1.8092,  1.7406,  0.6759,  1.1249],
        [-0.4173, -0.3692,  0.6149,  1.2380],
        [ 0.0894,  2.6567, -0.4502, -1.2673],
        [ 1.6244,  0.6031,  1.4928,  2.4626]], device='cuda:0')
[[ 1.8092208   1.7405617   0.6759486   1.1249104 ]
 [-0.41731536 -0.36915398  0.6149081   1.2379774 ]
 [ 0.08935416  2.656694   -0.45022535 -1.2673371 ]
 [ 1.624419    0.6030699   1.4927666   2.4625907 ]]


In [ ]:
# Different bewteen ones_like and ones
# ones_like will have the same size as the input tensor
# ones will have the size you specify