# Import Pytorch Libraries

In [1]:
import torch

# Create Tensor From List

In [2]:
list_a = [1, 2, 3, 4]

tensor_a = torch.tensor(list_a)
tensor_a

tensor([1, 2, 3, 4])

# Display tensor shape, data type and device

In [3]:
tensor_a.shape

torch.Size([4])

In [4]:
tensor_a.dtype

torch.int64

In [5]:
tensor_a.device

device(type='cpu')

# Create Tensor From Numpy Array

In [11]:
import numpy as np

array_a = np.array([[1,2],
                   [3,4]])

array_b = np.array([[1,0],
                   [0,1]])

array_c = np.array([[3,3,3],
                   [3,4,3]])

In [12]:
tensor_a = torch.from_numpy(array_a)
tensor_b = torch.from_numpy(array_b)
tensor_c = torch.from_numpy(array_c)

# Incompatible Shape

In [13]:
tensor_a + tensor_c

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

# Addtion, Subtraction, Multiplication, Division

In [14]:
tensor_a + tensor_b

tensor([[2, 2],
        [3, 5]], dtype=torch.int32)

In [15]:
tensor_a - tensor_b

tensor([[0, 2],
        [3, 3]], dtype=torch.int32)

In [16]:
tensor_a * tensor_b

tensor([[1, 0],
        [0, 4]], dtype=torch.int32)

In [17]:
tensor_a / tensor_b

tensor([[1., inf],
        [inf, 4.]])